### ISSUE TITLE
Issue while importing translated custom entity via Easy Translator

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/MsCrmTools.Translator#13]
@jalakraval123 commented on [Thu Aug 16 2018](https://github.com/MscrmTools/XrmToolBox/issues/797)

We're using the plug-in called "Easy Translation" to Import/Export Import translated entity and field text.

We're facing the below error's while importing the translated custom entity. 

[MsCrmTools.Translator.log](https://github.com/MscrmTools/XrmToolBox/files/2293721/MsCrmTools.Translator.log)

Could you please help us to troubleshoot this issue? How we can identify where we need to focus to resolve this error?

Thank you

**Comment by katzenbe** [comment]
Looks like the exported Excel is not getting the proper headers.

Version 1.2018.7.28

I selected all entities, checked only "Export Dashboards custom labels Translation" and exported. Excel worksheets 'Dashboards Tabs' and 'Dashboards Sections' did not have header rows. Made changes to 1033 columns in "Dashboards" and "Dashboard Fields". Reimported. 1033 changes were imported and published.  Error below appeared.

Error	Dashboards Tabs	Object reference not set to an instance of an object.
Error	Dashboards Sections	Object reference not set to an instance of an object.

**Comment by MscrmTools** [comment]
related to #18 
Will be fixed with #18
