### ISSUE TITLE
Easy translator : problem with single line of text with format URL

### ISSUE THREAD

**Issue by liesbetclaes** [MscrmTools/MsCrmTools.Translator#17]
A single line of text field on a form, with the format of URL is changed after reimporting the translation file (with easy translator).  The field has now a format of TEXT instead of URL, and cannot be used anymore as a clickable link.

**Comment by MscrmTools** [comment]
Thank you for reporting the issue.
Looking at the code, when updating an attribute, the full definition of the attribute is retrieved, then label and/or description are changed, then the attribute is updated.
I will need to try a repro and contact Microsoft if I can reproduce the issue

**Comment by MscrmTools** [comment]
I was not able to reproduce your issue. 

Can you confirm it is still happening?
