### ISSUE TITLE
Cannot import the translation file

### ISSUE THREAD

**Issue by maricasoderstam** [MscrmTools/MsCrmTools.Translator#2]
Hi, 

I'm trying to import a translation where we have complemented with another language and I get the following error message. I can't really tell whats wrong but hopefully you might be able to help me.

Thanks in advance!

![2017-03-17 09_56_49-xrmtoolbox for microsoft dynamics crm 2011 to 2016 v1 2017 2 13 - easy translate](https://cloud.githubusercontent.com/assets/26480071/24036090/5f90bf96-0af8-11e7-83eb-df69a0fe3414.png)

**Comment by MscrmTools** [comment]
Hi what is the version of Easy Translator you are using?

**Comment by maricasoderstam** [comment]
@MscrmTools I fixed it myself. Was some kind of restrict activated in the file when i tried to import which resulted in this error. You can close this :)
