### ISSUE TITLE
Translations for Workflow lablels not exported

### ISSUE THREAD

**Issue by michaelmberger** [MscrmTools/MsCrmTools.Translator#20]
One line summary of the problem: Translations for Workflow lablels not exported  
Full description of the problem/report: I have created a new Process of Category Business Process Flow. I added step labels to the steps.   
When I export translations for my solution, the workflow label is not exported. Can an import/export functionality for workflows be added to the plugin?
Keywords: Workflow, translations  
Version: 8.2.x  
Attached are the exported solution, Translation file from Easy Translator and translation export from CRM. The label in question has the content BugDemoTranslatableStep  

[BugDemo_1_0_0_0.zip](https://github.com/MscrmTools/MsCrmTools.Translator/files/3418247/BugDemo_1_0_0_0.zip)
[BugDemo.xlsx](https://github.com/MscrmTools/MsCrmTools.Translator/files/3418250/BugDemo.xlsx)
[CrmTranslations_BugDemo_1_0_0_0-4.zip](https://github.com/MscrmTools/MsCrmTools.Translator/files/3418254/CrmTranslations_BugDemo_1_0_0_0-4.zip)

**Comment by MscrmTools** [comment]
as far as I know, there is now way through SDK to export/import workflow and workflow steps labels
