### ISSUE TITLE
Entity Logical Name not populating in the exported file

### ISSUE THREAD

**Issue by naveedmcp** [MscrmTools/MsCrmTools.Translator#21]
@MscrmTools 
If I just export views after selecting multiple entities. I see that Entity Logical Name column in the exported excel.
![image](https://user-images.githubusercontent.com/31393621/61802718-f11cb680-adfe-11e9-9739-d1e81bdf874e.png)

**Comment by rappen** [comment]
Just got exactly the same!
![image](https://user-images.githubusercontent.com/2572253/68530566-935a9e80-0309-11ea-8fa5-5ecd94101a0d.png)

**Comment by MscrmTools** [comment]
Ok, let me check that!
