### ISSUE TITLE
Unexpected Results of translated form tabs, sections and form fields

### ISSUE THREAD

**Issue by BartM-NL** [MscrmTools/MsCrmTools.Translator#25]
I can't figure out why Easy Translator gives other results for the same label-GUID.
When I export form tabs, form sections and form fields my results are not consequent. When I select entities from two different solutions (both unmanaged) I can get for instance the french translation (1036) in the first solution and the german (1031) in the other. And after imported my changes and then export again, I will not always see my changed translations. And if I make an export via Load all entities of the same forms I can get other results. With other results I mean "not translated" labels.

For instance, entity Account, form Default, form tab Connections is in my export based on all entities of the solution no German or French translation. If I do the same by choosing just the specified entity I got another result. And if I choose the entity via Load all entities it is also different. The strange thing though is that when I test the form I see it is translated well. How does Dynamics know?
And my real problem is, that at this way I can't check if all is translated.

**Comment by MscrmTools** [comment]
Working with multiple languages, I change the UI language for the user to get all translations for each language. It seems that Dynamics server takes some time to apply this UI language change. 
I will add a pause to let Dynamics server to apply the change. That should fix the issue when exporting translations for forms

**Comment by Ezeckiel2517** [comment]
From time to time I got the same issue. French translation become all empty.

Is there any config to change to pause delay?
