### ISSUE TITLE
Importing translations

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/MsCrmTools.Translator#3]
@twanninger commented on [Mon Apr 11 2016](https://github.com/MscrmTools/XrmToolBox/issues/397)

I have been working on importing languages into my CRM environment via the Easy Translator tool in the XRM Toolbox.  I would continue running into errors when it would get to the _base fields.  This has been an issue in the past so I removed all the _base fields from the translation document and tried importing again.  After running for 25 minutes the import fails and gives me the attached error.  I was hoping someone might be able to tell me what the issue is, we have 8 languages to get translated and imported back into the system.
Tanya Wanninger
608.220.6042
![easy translator error](https://cloud.githubusercontent.com/assets/18405793/14439710/29241014-fff2-11e5-8393-17ae71704f10.jpg)

---

@arow44 commented on [Fri Jul 08 2016](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-231351537)

I have same problems (both). Did you solve it? 
Thanks

---

@twanninger commented on [Fri Jul 08 2016](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-231353589)

No, I wasn’t able to get it resolved using XRMToolbox.  I ended up using the CRM OOTB translations, they were able to import successfully.

From: arow44 [mailto:notifications@github.com]
Sent: Friday, July 8, 2016 7:53 AM
To: MscrmTools/XrmToolBox XrmToolBox@noreply.github.com
Cc: Tanya Wanninger TWanninger@hitachi-solutions.com; Author author@noreply.github.com
Subject: Re: [MscrmTools/XrmToolBox] Importing translations (#397)

I have same problems (both). Did you solve it?
Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-231351537, or mute the threadhttps://github.com/notifications/unsubscribe/ARjZoZ3NjWu8YD27EtwlyPOLdrUpZkb_ks5qTkgdgaJpZM4IEvC_.

Hitachi Solutions America is a company registered in the United States with registration number 3127998 whose registered office is at 851 Traeger Ave., Suite 200, San Bruno, CA 94066. This e-mail is intended solely for the person or entity to which it is addressed and may contain confidential and/or privileged information. Any review, dissemination, copying, printing or other use of this e-mail by persons or entities other than the addressee is prohibited. If you have received this e-mail in error, please contact the sender immediately and delete the material from any computer.

---

@JDHannan commented on [Wed Jul 20 2016](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-233990442)

I have this exact same problem.  I tried doing it with just one of our custom entities and just one language and it gives me the same exact error message.  I'm not sure what twanninger is saying about _base fields either so I can't attempt to remove them. It gives me the error in only a few seconds.

---

@JDHannan commented on [Wed Jul 20 2016](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-233994376)

Even if I take the file it exports and try to import that, it fails
I am using CRM 2015 0.2 on prem

---

@mscottsewell commented on [Wed Jul 20 2016](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-234009360)

@JDHannan  - try exporting with none of the 'global options' and only the first of the "entity related options" check marks selected - If that works, add a few more options and re-test - maybe you can isolate which of the options is creating the challenge.
In one environment on one entity I experienced this with one of the options (I can't remember which one.) - and if I exported all but that one, it worked. 
On subsequent environments/entities, I could choose all the options without error.

---

@MscrmTools commented on [Wed Jul 20 2016](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-234012770)

I'm still in holidays but I'm jumping in...

The error message talks about relationship translation error. Try to avoid exporting it until i find out why the problem is

---

@JDHannan commented on [Wed Jul 20 2016](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-234018348)

MScottSewell> That was a good idea, I reduced it down to what you suggested and it did work. I didn't actually mean to import it, I tried to click on the Import tab, but clicked the Import button and it must have been already filled in from a previous attempt and it just imported the fresh export.
I've also been messing around with the standard (and terrible) CRM way of doing translations and in the end, I had tonnes of things labelled #REF 
I have restored a backup of my org and as per MscrmTools' indication, I am not going to play with it anymore for the time being.

---

@JDHannan commented on [Fri Jul 29 2016](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-236277551)

I finally got back around to looking at this again and it fails only when i pick the very last option - Export Relationships that are using custom labels.

Hope that helps

---

@maricasoderstam commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-287694686)

I have the same issue! Any updates?

---

@MscrmTools commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-287697560)

I can work on this today... stay tuned!

---

@MscrmTools commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-287702933)

@maricasoderstam @JDHannan Can you confirm if the error still exists with latest version? I exported a relationship with custom label, tried to import it back with or without value for not translated label and it does not fail...

---

@maricasoderstam commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-287722298)

@MscrmTools I downloaded the latest and greatest and the error still occurs. I get the following error.

It could be something in my file but I haven't been able to identify it. 

![2017-03-20 11_27_25-xrmtoolbox for microsoft dynamics crm 2011 to 2016 v1 2017 2 13](https://cloud.githubusercontent.com/assets/26480071/24096068/40a7038c-0d60-11e7-93d0-ebfa0db15777.png)

---

@MscrmTools commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-287726939)

May I have the spreadsheet with data? 

---

@maricasoderstam commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-287736423)

[EasyTranslator - MUA1.XLSX](https://github.com/MscrmTools/XrmToolBox/files/854615/EasyTranslator.-.MUA1.XLSX)

---

@MscrmTools commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-287800753)

I guess I found the issue... You have one relationship without any translation, even for the base langage.
If I apply the same in my sample file, I get the same error
![image](https://cloud.githubusercontent.com/assets/10774317/24107952/805b5f88-0d8c-11e7-80a7-d73309d903b3.png)

---

@MscrmTools commented on [Mon Mar 20 2017](https://github.com/MscrmTools/XrmToolBox/issues/397#issuecomment-287801098)

By the way, I'm moving the issue in the appropriate repository, please contine the discussion there

**Comment by maricasoderstam** [comment]
I think it's because it uses the plural name of the entity instead of a custom label.

**Comment by JDHannan** [comment]
I have done an export with the tool, then done a re-import with no changes and re-imported it and had it not work as i said on July 16 above. While it might be true that having no translation for the base language breaks it, it seems like the tool shouldn't export something it can't re-import. Either have it export the default value for the default language, or have it ignore rows with nothing in the base language column?

**Comment by MscrmTools** [comment]
I think I'm retrieving only those with a custom label

```
if (!rel.AssociatedMenuConfiguration.Behavior.HasValue ||
    rel.AssociatedMenuConfiguration.Behavior.Value != AssociatedMenuBehavior.UseLabel)
       continue;

Or it means that "normal" relationships does have a null `Behavior`property

**Comment by maricasoderstam** [comment]
I think the issue is that on one of the entities I'm using the plural name and the other has a custom label. So maybe that has something to do with it?

**Comment by MscrmTools** [comment]
Good catch! So this is a NN relationship with one custom label et one plural name, am I correct?

**Comment by MscrmTools** [comment]
Ok, found the issue, code is ready to ship but I will add small improvements before that
