### ISSUE TITLE
Translation of custom Button, Menu labels

### ISSUE THREAD

**Issue by v22arvind** [MscrmTools/MsCrmTools.Translator#30]
I exported custom entities and gave to translators. After importing the file back, during testing we found that Custom buttons are not translated.
I am trying to search the labels but am unable to find in the exported files.
Are these ribbon components not exported?

**Comment by v22arvind** [comment]
Ok - so I see the code there but its not enabled/integrated in the mail tool because RibbonDiff entity doesn't accept updates.
I ended up doing a quick and dirty tool to
1. Export the data from RibbonDiff and then filter the unnecessary entities out.
2. For import, I first export the unmanaged solution file (managed should also work I believe) and then update the customization.xml using my quick/dirty tool. Then I import the solution file back in CRM. It would be interesting to know how microsoft handles the translation during import in CRM and try to do that.

**Comment by MscrmTools** [comment]
As you found out, there is no way to update RibbonDiff element so that won't be included in this tool
