### ISSUE TITLE
Import big file is too slow

### ISSUE THREAD

**Issue by TencentLee** [MscrmTools/MsCrmTools.Translator#34]
Can we import translations by executing multiple requests?
The source code uses service.execute to update data, but for large files, a single request can be too slow.

**Comment by MscrmTools** [comment]
Sure! Let me work on this

**Comment by TencentLee** [comment]
> Sure! Let me work on this

This tool is very good. Great job!

**Comment by MscrmTools** [comment]
It has been deliverd as part of the latest release
