### ISSUE TITLE
the form contents are updated twice

### ISSUE THREAD

**Issue by TencentLee** [MscrmTools/MsCrmTools.Translator#35]
The When the ImportFormsContent method is executed, it appears that parts of the form contents are updated twice.

if (hasFormContent)
                {
                    worker.ReportProgressIfPossible(0, new ProgressInfo
                    {
                        Message = "Importing form content translations...",
                        Item = 1,
                        Overall = overallProgress == 0 ? 1 : overallProgress * 100 / count
                    });
                    ft.BatchSize = this.BatchSize;
                    ft.ImportFormsContent(service, **forms**, worker);
                }

if (hasDashboardContent)
                {
                    worker.ReportProgressIfPossible(0, new ProgressInfo
                    {
                        Message = "Importing dashboard content translations...",
                        Item = 1,
                        Overall = overallProgress == 0 ? 1 : overallProgress * 100 / count
                    });
                    db.BatchSize = this.BatchSize;
                    db.ImportFormsContent(service, **forms**, worker);
                }

**Comment by MscrmTools** [comment]
You are correct. I will store dashboards on their own list so that it's not updated twice.
Thank your for reporting
