### ISSUE TITLE
Not importing Entity, Attribute, Option Set and Boolean

### ISSUE THREAD

**Issue by ShaggyAbakion** [MscrmTools/MsCrmTools.Translator#37]
Hi there,

I have several times tried to update Entity, Attribute, Option Set and Boolean but no luck.

Se image below. Please help. 

![image](https://user-images.githubusercontent.com/43342754/84087496-82325700-a9ea-11ea-80fe-ce4d9f37c956.png)

**Comment by MscrmTools** [comment]
Can you share the log file?

**Comment by MscrmTools** [comment]
@ShaggyAbakion answering using email does not send images you pasted in your email. Please answer throught Github website.
When import is complete, you should have an "open log file" link at the top of the progress panel

**Comment by ShaggyAbakion** [comment]
Hi there,

I am getting this error all the time
![image](https://user-images.githubusercontent.com/43342754/85235921-5dda6f80-b419-11ea-9765-f5681fc05131.png)

and it stucjs here. There is no log

![image](https://user-images.githubusercontent.com/43342754/85237470-6f2a7880-b427-11ea-9400-d0cc3af73470.png)

**Comment by MscrmTools** [comment]
The error message indicates a timeout. You need to raise the timeout of you connection so that the import process can last more tha,n 2 minutes
