### ISSUE TITLE
When exporting Forms Section, Forms Tab, Forms Attributes, the existing translation are not exported.

### ISSUE THREAD

**Issue by StephaneSeguin** [MscrmTools/MsCrmTools.Translator#38]
I'm Using version 1.2020.5.12 for CRM 8.2

Cannot add Screenshot, the site wont let me.

**Comment by MscrmTools** [comment]
Can you precise if no rows are exported or if only non base language translations are not exported?

**Comment by StephaneSeguin** [comment]
> re exported or if only non base language translations are not exported?
Hello,
I noticed that when I select all options, then the Forms Section, Forms Tab, Forms Attributes the base language is exported but not the extra language.  When I select only  Forms Section, Forms Tab, Forms Attributes then the extra language is exported.

Base language, 1033, Extra language 1036.

**Comment by MscrmTools** [comment]
Thank you for these precisions, I will check the code

**Comment by MscrmTools** [comment]
I just did a test on D365 online and everything worked as expected... Same situation => Base language, 1033, Extra language 1036.
All options checked => ok
Only Forms Tabs, Forms Sections and Forms Fields => ok too

I will try to find an 8.2 organization to try to reproduce

**Comment by StephaneSeguin** [comment]
I found why. If my user that used in CRM is not in the base language, when I use the XRMtoolBox the translation are not exported for these options.

**Comment by MscrmTools** [comment]
thank you! that helps a lot! I will check the code for that particular configuration
