### ISSUE TITLE
System.TimeoutException

### ISSUE THREAD

**Issue by Martype** [MscrmTools/MsCrmTools.Translator#39]
Hi, when importing the translation file I get a System.TimeoutException. It first appeared after step "Form Contents". I then split up the excel and removed everything prior to the "Forms" sheet. The second and third run also ended up in a System.TimeoutException after step "Sitemaps".
This probably happens when the imported translations become published, right? If that's the case I'd even say that error can be ignored safely, since the publishing process would finish on D365 anyways. Please confirm or decline.

![image](https://user-images.githubusercontent.com/1420317/88523010-885eb000-cff7-11ea-8f0b-dacae36b8310.png)

**Comment by MscrmTools** [comment]
You just should raise the timeout of your connection to avoid this issue
