### ISSUE TITLE
Not Processing Attributes Translations

### ISSUE THREAD

**Issue by alexmare93** [MscrmTools/MsCrmTools.Translator#41]
Hi,

I noticed that by importing translations, the Attributes, Optionset and Booleans tabs are not considered, calculating the total but not processing them at all:

![immagine](https://user-images.githubusercontent.com/57076004/90877678-c1930180-e3a4-11ea-967f-caa15d6abd06.png)

Could you verifiy?

Thank you,
Alessandro
---
- Deployment: OnPremise
- DB Version: 8.2.3.8
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2020.7.13

**Comment by falstaffjobs** [comment]
Same issue here, trying to import 264 account attributes but 0 processed or failed
<img width="1434" alt="Bildschirmfoto 2020-09-02 um 15 40 24" src="https://user-images.githubusercontent.com/10829964/91936452-3bc36e80-ed33-11ea-90e8-4c86c1b95f7f.png">

**Comment by MscrmTools** [comment]
Thank you for reporting, I will check this

**Comment by MscrmTools** [comment]
Hi guys, I found the issue which was a timeout issue.
Added possibility to set the batch requests quantity and an explicit log
Can you please test with this version

[MsCrmTools.Translator.zip](https://github.com/MscrmTools/MsCrmTools.Translator/files/5218803/MsCrmTools.Translator.zip)

**Comment by MscrmTools** [comment]
Fixed in latest version
