### ISSUE TITLE
Error importing Booleans

### ISSUE THREAD

**Issue by falstaffjobs** [MscrmTools/MsCrmTools.Translator#43]
I have trouble importing Boolean Translations on a custom entity:
![Bildschirmfoto 2020-10-13 um 11 20 48](https://user-images.githubusercontent.com/10829964/95801740-0ef97280-0d47-11eb-918b-eff2b7a0d428.png)

that's the template I get when I export the booleans:
![Bildschirmfoto 2020-10-13 um 11 27 51](https://user-images.githubusercontent.com/10829964/95801784-305a5e80-0d47-11eb-9df1-66ec688cb011.png)

**Comment by MscrmTools** [comment]
Can you translate the error message in english?
