### ISSUE TITLE
Export SiteMap custom labels Translation -> An item with same key has already been added

### ISSUE THREAD

**Issue by rpdom1337** [MscrmTools/MsCrmTools.Translator#44]
Hi,

When i just select Global Options  "Export SiteMap custom labels Translation", and i choose my unmanaged solution, i get this exception:
![image](https://user-images.githubusercontent.com/58991535/99590081-2a623800-29ed-11eb-9c3a-865952976226.png)

Do you have any idea what the cause of the  probem?
I have newest versions installed.

Thanks a lot for helping.

**Comment by MscrmTools** [comment]
The only way to get this exception according to the code would be to have multiple titles or descriptions for the same item with the same language.
