### ISSUE TITLE
object not set to an instance error when importing dashboard labels

### ISSUE THREAD

**Issue by manuelstiphout** [MscrmTools/MsCrmTools.Translator#46]
i'm getting this error when importing translated labels for a dashboard....

![image](https://user-images.githubusercontent.com/76054849/102230874-aae15f00-3eed-11eb-819c-c92d1361295f.png)

any ideas how to solve this?

**Comment by MscrmTools** [comment]
What is your version of translator tool?

**Comment by manuelstiphout** [comment]
i've updated xrm toolbox to 10.41 but i still get the same error. the easytranslator tool is on the latest version

**Comment by manuelstiphout** [comment]
easytranslator is on 1.2020.9.14

**Comment by MscrmTools** [comment]
And what is the version of the environment you are using? So that I can try to reproduce

**Comment by manuelstiphout** [comment]
Version 1710 (9.1.0.25849) online
