### ISSUE TITLE
Import is not working for Quick view form section names

### ISSUE THREAD

**Issue by cleitonsantos** [MscrmTools/MsCrmTools.Translator#51]
Reproduction Steps:
- On a multi-language instance create a quick view form
- Export the translations for form sections only (doesn't matter if you do for options or just for form sections, results are the same)
- Update the translations for the section title
- Import back the tranlations

Expected:
**The form section title should be imported properly**

Result
**For any section the translations has no effects. Also if you try to switch the English (or default language) name during the translation process it doesn't change**

---
- Deployment: Online
- DB Version: 9.2.22061.158
- Connection Controls Version: 1.2022.5.51
- XrmToolBox Version: 1.2022.5.56
- Tool Version: 1.2022.2.18

**Comment by MscrmTools** [comment]
Hi @cleitonsantos, I know there is something not working anymore when working with sections, tabs and form fields...
But I'm not sure I can do something to fix this. 
I need to find more time to investigate this point

**Comment by MscrmTools** [comment]
I think I finally succeeded to fix this issue! A new version is coming in the next hours or so. Please test it to validate it works as expected

**Comment by MscrmTools** [comment]
Great news, I finally found a remaining bug that I have fixed and that should fix all these issues! New release to come
