### ISSUE TITLE
Tried a simple test to update German labels for 1 field on Work Order table - Timed Out!

### ISSUE THREAD

**Issue by paulboiano** [MscrmTools/MsCrmTools.Translator#57]
Changed one German translation of both Attribute (schema field display name) and form label - timed out at 2 minutes. Progress bar never moved. 
2022-12-05 10:56:31.022 AM	IPG DEV	Info	Reading Attributes
2022-12-05 10:56:31.309 AM	IPG DEV	Info	Importing Attributes translations
2022-12-05 10:58:31.577 AM	IPG DEV	Error	Timeout! Please reduce batch size or increase your connection timeout

Is it best to remove all the other fields that I had exported (all attributes and all form fields) that I did not change and only leave the rows in the file that I did change? 

Is there some type of user manual / best practices doc for this tool? When I click on "Get Help for Easy Translator, it opens the main GitHub page for the project, but I don't see any user manual type documentation. 

BTW, the export translations function works GREAT! Very user friendly and easy to use to obtain "current status" of translations. 
Thanks. 
---
- Deployment: Online
- DB Version: 9.2.22103.214
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2022.11.59
- Tool Version: 1.2022.7.21

**Comment by MscrmTools** [comment]
Hi @paulboiano , you can definitively delete rows you are not translating to reduce the volume of translations to process.

You can also increase the timeout of your XrmToolBox connection, and reduce the batch size
