### ISSUE TITLE
Form Content does import multiple times

### ISSUE THREAD

**Issue by exxlez** [MscrmTools/MsCrmTools.Translator#58]
When importing Form Contents, the Batch Number is increasing until it reaches the Sum (Here 30). After that the Import does start from 0 again and goes up again. This happens multiple Times until a timeout is reached or the publish is finally starting (often after hours).

![image](https://user-images.githubusercontent.com/80924175/211837175-26e0f4ca-e640-4594-9e8a-f483a824b71e.png)

**Comment by MscrmTools** [comment]
@exxlez I'm not sure it's a bug. Forms content have to be imported on a per language basis, so I assume counter restart as many times as there are different languages.
Does it make sense or should I change something?

**Comment by exxlez** [comment]
So it is repeated as many times as there are different language columns in the Excel file? Or is the repetition based on the languages enabled in the system? Because even though there is only one language column in Excel, the process is repeated.

**Comment by MscrmTools** [comment]
Good catch, it's processing for each language enabled in the environment. 
I will check how to change this behavior to process only languages from the Excel file
