### ISSUE TITLE
Query on Entity has exceeded the hard limit of conditions in a single filter (300)

### ISSUE THREAD

**Issue by DarylOrwin** [MscrmTools/MsCrmTools.Translator#60]
I get this error when exporting translations for a large solution: 
![image](https://user-images.githubusercontent.com/2320447/212898018-8a329bf8-4567-4f58-adff-71eac5406bbb.png)

**Comment by MscrmTools** [comment]
@DarylOrwin I think the issue is more when you load tables from a large solution than when exporting. Exporting does not create a metadata query. am I correct?

**Comment by DarylOrwin** [comment]
Hi.  This was just loading the list of tables when selecting the solution.  If I don't use a solution it is able to load all entities.  So must be some filter related to the solution I imagine.
