### ISSUE TITLE
Entity Collectionnames are not exported with Easy Translator.

### ISSUE THREAD

**Issue by exxlez** [MscrmTools/MsCrmTools.Translator#61]
When exporting Entity Translations, the correct Labels are exported, but the "DisplayCollectionName" is empty for every Entity even there are som Collectionnames already in the system. I tried it with different Entities, Languages and on different days. 

![image](https://user-images.githubusercontent.com/80924175/220641961-e321e8f1-ec5e-4460-9b7b-34ee771d3bec.png)

![image](https://user-images.githubusercontent.com/80924175/220642208-56a8f629-d17e-4c84-bff9-5405cd988314.png)

**Comment by MscrmTools** [comment]
Fixed in latest version
