### ISSUE TITLE
Error System.TimeoutException / System.Net.WebException when import only 17 Entity Translation 

### ISSUE THREAD

**Issue by rivaiwardhana** [MscrmTools/MsCrmTools.Translator#62]
I have an error when importing only 17 entity translation english and japanese with Batch count only 10, but its worked with 15 entity only. so I import every 15 from 600entities to be translated. and with form view sitemap this error is does not show even i have 2000-5000 record translate. this happen only in entity translation. why this error is always show if i imported more than 15 entities? and are there any setting in CRM which I missed to set before using this tools?
![Error IO Exception](https://user-images.githubusercontent.com/61689177/224283624-2f1c4305-5cbc-49d3-8cdd-1ebbf9fc4486.PNG)
![error 9](https://user-images.githubusercontent.com/61689177/224283704-bb41b1be-1a50-4a54-8e3c-d139e2a59f6e.PNG)
![erroor3](https://user-images.githubusercontent.com/61689177/224283772-8e23d072-6c48-41ad-81d4-094d
![17Error](https://user-images.githubusercontent.com/61689177/224283830-7bf5f4a9-ccbb-4ab8-b6ea-67a3d6d5c621.PNG)
![optionset success](https://user-images.githubusercontent.com/61689177/224283886-72f9a254-996c-4aa5-834c-cee5d3fccdc9.PNG)

72ecf341.PNG)
![Success15](https://user-images.githubusercontent.com/61689177/224284154-3950c702-5c69-4efa-9534-2bb29502681c.PNG)

**Comment by MscrmTools** [comment]
Hi @rivaiwardhana, I guess your best shot is to increase the timeout of your connection so that it does not fail after 2 minutes.

To do so, edit your connection in Connection Manager and set a timeout of at least 10 minutes

**Comment by rivaiwardhana** [comment]
> Hi @rivaiwardhana, I guess your best shot is to increase the timeout of your connection so that it does not fail after 2 minutes.
> 
> To do so, edit your connection in Connection Manager and set a timeout of at least 10 minutes

thank you for the response. last time i was use **microsoft Login control** to crate connection, so i dont find the service timeout, now i have change the connection method with **connection wizard** and set the service timeout 10 minutes, it seems work nicely thanks a lot

**Comment by rivaiwardhana** [comment]
thank you
