### ISSUE TITLE
Object referene exception while importing the translation file

### ISSUE THREAD

**Issue by naveedmcp** [MscrmTools/MsCrmTools.Translator#7]
Hi,
While importing back the translation, I am getting following error. I have kept all the validations which were mentioned in the import module guidelines but unfortunately getting the error. For security reasons, I have removed the server names and timestamp from the logs.

Error      Relationships     1:1
Error      Relationships     2:1
Error      Relationships     3:1
Error      Global OptionSets                mobileofflineenabledentities: Could not find a picklist value with specified value: 2
Error      Global OptionSets                mobileofflineenabledentities: Could not find a picklist value with specified value: 3
Error      Global OptionSets                mobileofflineenabledentities: Could not find a picklist value with specified value: 4
Error      Global OptionSets                mobileofflineenabledentities: Could not find a picklist value with specified value: 8
Error      Global OptionSets                mobileofflineenabledentities: Could not find a picklist value with specified value: 4201
Error      Global OptionSets                mobileofflineenabledentities: Could not find a picklist value with specified value: 4202
Error      Views    Object reference not set to an instance of an object.
Error      Forms   Object reference not set to an instance of an object.
Error      Forms Tabs         Object reference not set to an instance of an object.
Error      Forms Sections  Object reference not set to an instance of an object.
Error      Forms Fields       Object reference not set to an instance of an object.
Error      Dashboards Fields            Object reference not set to an instance of an object.

**Comment by MscrmTools** [comment]
Shouldn't be an issue anymore. If so, please reopen
